<?php
/**
 * @file
 * Contains applications.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;


function registration_form_form_alter(&$form, FormStateInterface $form_state, $form_id){
  if($form_id=="student_registration_form" ){
      $form['actions']['submit']['#submit'][] = 'modulename_user_edit_form_submit';
  }
 

}
function modulename_user_edit_form_submit($form,  FormStateInterface &$form_state) {
  global $base_url; //set base path
  $response = new Symfony\Component\HttpFoundation\RedirectResponse($base_url ."/node/4"); //set url
  $response->send();
  return;
}
